/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    head_slot: THREE.SkinnedMesh;
  };
  materials: {
    vertex_color: THREE.MeshBasicMaterial;
  };
};

const HeadSlot = (props: React.JSX.IntrinsicElements["skinnedMesh"]) => {
  const model = useGLTF(`models/cosmetic_${props.name}.glb`) as GLTFResult;
  return (
    <skinnedMesh
      {...props}
      name={props.name}
      geometry={model.nodes.head_slot.geometry}
      material={model.materials.vertex_color}
    />
  );
};

export default HeadSlot;
