/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { usePomodoro } from "../../utils/usePomodoro";
import * as THREE from "three";
import { TextureLoader } from "three/src/loaders/TextureLoader.js";
import { GLTF } from "three-stdlib";
import { useLoader } from "@react-three/fiber";

type ActionName =
  | "break"
  | "continue_study"
  | "none"
  | "start_break"
  | "start_study"
  | "study";
// type GLTFActions = Record<ActionName, THREE.AnimationAction>;

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    monkey: THREE.SkinnedMesh;
    root: THREE.Bone;
    ["MCH-torsoparent"]: THREE.Bone;
    ["MCH-hand_ikparentL"]: THREE.Bone;
    ["MCH-upper_arm_ik_targetparentL"]: THREE.Bone;
    ["MCH-hand_ikparentR"]: THREE.Bone;
    ["MCH-upper_arm_ik_targetparentR"]: THREE.Bone;
    ["MCH-foot_ikparentL"]: THREE.Bone;
    ["MCH-thigh_ik_targetparentL"]: THREE.Bone;
    ["MCH-foot_ikparentR"]: THREE.Bone;
    ["MCH-thigh_ik_targetparentR"]: THREE.Bone;
  };
  animations: GLTFAction[];
};

const filePath = "/models/pomodoro_pets_monkey_1_v2.glb";

const material = new THREE.MeshBasicMaterial();

export default function Monkey(props: JSX.IntrinsicElements["group"]) {
  const { pomodoroPhase, currentRound, modelLoaded } = usePomodoro();
  const group = useRef<THREE.Group>(null);
  const { nodes, animations } = useGLTF(filePath, true, undefined, (loader) => {
    loader.manager.onLoad = () => {
      modelLoaded();
    };
  }) as GLTFResult;
  const { actions } = useAnimations<GLTFAction>(animations, group);

  const texture = useLoader(TextureLoader, "textures/monkey_1_diffuse.png");
  texture.flipY = false;
  texture.minFilter = THREE.NearestFilter;
  texture.magFilter = THREE.NearestFilter;

  useEffect(() => {
    if (pomodoroPhase === "none") {
      actions.none?.reset().fadeIn(0.5).play();
      return () => actions.none?.fadeOut(0.5);
    } else if (pomodoroPhase === "work" && currentRound === 0) {
      const duration = actions.start_study?.getClip().duration || 2;
      actions.start_study
        ?.reset()
        .fadeIn(0.5)
        .setLoop(THREE.LoopOnce, 0)
        .play();

      if (actions.start_study && !actions.start_study?.clampWhenFinished)
        actions.start_study.clampWhenFinished = true;

      const delayedAction = setTimeout(() => {
        actions.study?.reset().fadeIn(0).play();
      }, duration * 1000);

      return () => {
        actions.start_study?.fadeOut(0.5);
        actions.study?.fadeOut(0.5);
        clearTimeout(delayedAction);
      };
    } else if (pomodoroPhase === "break") {
      const duration = actions.start_break?.getClip().duration || 2;
      actions.start_break
        ?.reset()
        .fadeIn(0.5)
        .setLoop(THREE.LoopOnce, 0)
        .play();

      if (actions.start_break && !actions.start_break?.clampWhenFinished)
        actions.start_break.clampWhenFinished = true;

      const delayedAction = setTimeout(() => {
        actions.break?.reset().fadeIn(0).play();
      }, duration * 1000);

      return () => {
        actions.start_break?.fadeOut(0.5);
        actions.break?.fadeOut(0.5);
        clearTimeout(delayedAction);
      };
    } else if (pomodoroPhase === "work" && currentRound > 0) {
      const duration = actions.continue_study?.getClip().duration || 2;
      actions.continue_study
        ?.reset()
        .fadeIn(0.5)
        .setLoop(THREE.LoopOnce, 0)
        .play();

      if (actions.continue_study && !actions.continue_study?.clampWhenFinished)
        actions.continue_study.clampWhenFinished = true;

      const delayedAction = setTimeout(() => {
        actions.study?.reset().fadeIn(0).play();
      }, duration * 1000);

      return () => {
        actions.continue_study?.fadeOut(0.5);
        actions.study?.fadeOut(0.5);
        clearTimeout(delayedAction);
      };
    }
  }, [pomodoroPhase, currentRound, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="monkey_rig">
          <skinnedMesh
            name="monkey"
            geometry={nodes.monkey.geometry}
            material={material}
            material-map={texture}
            skeleton={nodes.monkey.skeleton}
          />
          <primitive object={nodes.root} />
          <primitive object={nodes["MCH-torsoparent"]} />
          <primitive object={nodes["MCH-hand_ikparentL"]} />
          <primitive object={nodes["MCH-upper_arm_ik_targetparentL"]} />
          <primitive object={nodes["MCH-hand_ikparentR"]} />
          <primitive object={nodes["MCH-upper_arm_ik_targetparentR"]} />
          <primitive object={nodes["MCH-foot_ikparentL"]} />
          <primitive object={nodes["MCH-thigh_ik_targetparentL"]} />
          <primitive object={nodes["MCH-foot_ikparentR"]} />
          <primitive object={nodes["MCH-thigh_ik_targetparentR"]} />
        </group>
      </group>
    </group>
  );
}
