/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { usePomodoro } from "../utils/usePomodoro";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type ActionName = "PositionOuterFrame" | "StartStudying" | "Studying";
// type GLTFActions = Record<ActionName, THREE.AnimationAction>;

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Cube5103: THREE.SkinnedMesh;
    Cube5103_1: THREE.SkinnedMesh;
    Cube5103_2: THREE.SkinnedMesh;
    body: THREE.Bone;
  };
  materials: {
    ["White.026"]: THREE.MeshStandardMaterial;
    ["Yellow.043"]: THREE.MeshStandardMaterial;
    ["Black.027"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

const filePath = "/models/duck_skinning_2.glb";

export default function Duck(props: JSX.IntrinsicElements["group"]) {
  const { pomodoroPhase, currentRound } = usePomodoro();
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(filePath) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    console.log(actions);

    if (pomodoroPhase === "none") {
      actions.PositionOuterFrame?.reset().fadeIn(0.5).play();
      return () => actions.PositionOuterFrame?.fadeOut(0.5);
    } else if (pomodoroPhase === "work" && currentRound === 0) {
      actions.StartStudying?.reset()
        .fadeIn(0.5)
        .setLoop(THREE.LoopOnce, 0)
        .play();

      if (actions.StartStudying?.clampWhenFinished)
        actions.StartStudying.clampWhenFinished = true;

      const delayedAction = setTimeout(() => {
        actions.Studying?.reset().fadeIn(0.5).play();
      }, 4200);

      return () => {
        actions.StartStudying?.fadeOut(0.5);
        actions.Studying?.fadeOut(0.5);
        clearTimeout(delayedAction);
      };
    } else {
      actions.Studying?.reset().fadeIn(0).play();
      return () => actions.Studying?.fadeOut(0.5);
    }

    /*  const action = actions[animationName()];
    if (!action) return;
    action.reset().fadeIn(0.5).setLoop(THREE.LoopOnce, 0).play();
    action.clampWhenFinished = true; */
    // return () => action.fadeOut(0.5);
  }, [pomodoroPhase, currentRound, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="DuckArmature">
          <group name="character_duck">
            <skinnedMesh
              name="Cube5103"
              geometry={nodes.Cube5103.geometry}
              material={materials["White.026"]}
              skeleton={nodes.Cube5103.skeleton}
            />
            <skinnedMesh
              name="Cube5103_1"
              geometry={nodes.Cube5103_1.geometry}
              material={materials["Yellow.043"]}
              skeleton={nodes.Cube5103_1.skeleton}
            />
            <skinnedMesh
              name="Cube5103_2"
              geometry={nodes.Cube5103_2.geometry}
              material={materials["Black.027"]}
              skeleton={nodes.Cube5103_2.skeleton}
            />
          </group>
          <primitive object={nodes.body} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(filePath);
