/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    cabinet: THREE.Mesh;
    room: THREE.Mesh;
    table: THREE.Mesh;
    chair: THREE.Mesh;
    outsidePlane: THREE.Mesh;
    curtain: THREE.Mesh;
    windowtop: THREE.Mesh;
    curtain001: THREE.Mesh;
  };
};

const material = new THREE.MeshBasicMaterial({color: 0xffffff});

export function Room(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(
    "/pomodoropet_layout_2.glb"
  ) as GLTFResult;
  const texture = useTexture("/baked_texture_2.jpg");
  texture.flipY = false;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet.geometry}
        material={material}
        material-map={texture}
        position={[-1.162, 0.01, -0.745]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.room.geometry}
        material={material}
        material-map={texture}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.table.geometry}
        material={material}
        material-map={texture}
        position={[-1.27, 0.677, 0.105]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair.geometry}
        material={material}
        material-map={texture}
        position={[-0.52, 0.437, 0.012]}
        rotation={[0, 0.489, 0]}
        scale={[1, 1, 1.818]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.outsidePlane.geometry}
        material={material}
        material-map={texture}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.curtain.geometry}
        material={material}
        material-map={texture}
        position={[-0.225, 0.57, -0.938]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.windowtop.geometry}
        material={material}
        material-map={texture}
        position={[0.227, 2.093, -0.993]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.curtain001.geometry}
        material={material}
        material-map={texture}
        position={[0.792, 0.57, -0.938]}
      />
    </group>
  );
}

useGLTF.preload("/pomodoropet_layout_2.glb");
